/**
 * SYNTHETIC DEMO FIXTURES — NOT AN OFFICIAL RECORD.
 * Strictly isolated fallback dataset matching FastAPI schemas for offline demo preview.
 */
import type {
  AuthenticatedPrincipal,
  BidderRead,
  ComplianceMatrixRead,
  ComplianceOverviewRead,
  IntegrationsHealthResponse,
  JobEventRead,
  ProviderHealthRead,
  ReportRead,
  TenderRead,
  TenderRequirementRead,
  VerificationResultRead,
} from '@/types/api';

export const MOCK_PRINCIPAL: AuthenticatedPrincipal = {
  user_id: 'argus-local-demo-officer',
  name: 'Demo Procurement Officer',
  email: 'demo.procurement@argus.local',
  role: 'PROCUREMENT_OFFICER',
};

export const MOCK_TENDERS: TenderRead[] = [
  {
    id: 'tender_gem_2026_01',
    tender_number: 'GEM/2026/B/4521089',
    title: 'Comprehensive Highway Surveillance & IT Infrastructure Modernization',
    category: 'GOODS_AND_SERVICES',
    authority: 'National Highways Authority of India',
    budget: 50000000,
    deadline: '2026-10-15T18:00:00Z',
    status: 'COMPLETED',
    created_at: '2026-08-01T10:00:00Z',
    updated_at: '2026-08-01T10:00:00Z',
  },
  {
    id: 'tender_gem_2026_02',
    tender_number: 'GEM/2026/B/4521090',
    title: 'National Digital Identity Verification & Cloud Backup Cluster',
    category: 'IT_INFRASTRUCTURE',
    authority: 'Ministry of Electronics & Information Technology',
    budget: 120000000,
    deadline: '2026-11-01T17:00:00Z',
    status: 'RUNNING',
    created_at: '2026-08-10T11:30:00Z',
    updated_at: '2026-08-10T11:30:00Z',
  },
  {
    id: 'tender_gem_2026_03',
    tender_number: 'GEM/2026/B/4521091',
    title: 'Smart Solar Grid Micro-Inverter Deployment (Phase IV)',
    category: 'RENEWABLE_ENERGY',
    authority: 'Solar Energy Corporation of India',
    budget: 85000000,
    deadline: '2026-12-01T12:00:00Z',
    status: 'QUEUED',
    created_at: '2026-08-20T09:15:00Z',
    updated_at: '2026-08-20T09:15:00Z',
  },
];

export const MOCK_REQUIREMENTS: TenderRequirementRead[] = [
  {
    id: 'req_01',
    tender_id: 'tender_gem_2026_01',
    clause: 'Clause 4.1.1',
    requirement_type: 'GST',
    field: 'tax.gstin',
    operator: 'EQ',
    expected_value: 'VALID_ACTIVE',
    unit: null,
    mandatory: true,
    source_page: 4,
    source_text: 'Bidder must possess a valid, active GSTIN registration in India.',
    confidence: 0.98,
    requires_verification: true,
    is_approved: true,
    metadata_json: {},
    created_at: '2026-08-01T10:05:00Z',
  },
  {
    id: 'req_02',
    tender_id: 'tender_gem_2026_01',
    clause: 'Clause 4.2.3',
    requirement_type: 'TURNOVER',
    field: 'financial.average_annual_turnover',
    operator: 'GTE',
    expected_value: 50000000,
    unit: 'INR',
    mandatory: true,
    source_page: 5,
    source_text: 'Minimum average annual turnover shall be INR 5,00,00,000 for the last 3 financial years.',
    confidence: 0.95,
    requires_verification: true,
    is_approved: true,
    metadata_json: {},
    created_at: '2026-08-01T10:05:00Z',
  },
  {
    id: 'req_03',
    tender_id: 'tender_gem_2026_01',
    clause: 'Clause 4.3.1',
    requirement_type: 'EXPERIENCE',
    field: 'experience.years',
    operator: 'GTE',
    expected_value: 3,
    unit: 'YEARS',
    mandatory: true,
    source_page: 7,
    source_text: 'Bidder must have at least 3 years of continuous operating experience in IT infrastructure.',
    confidence: 0.92,
    requires_verification: true,
    is_approved: true,
    metadata_json: {},
    created_at: '2026-08-01T10:05:00Z',
  },
  {
    id: 'req_04',
    tender_id: 'tender_gem_2026_01',
    clause: 'Clause 5.1.2',
    requirement_type: 'UDYAM',
    field: 'registration.udyam',
    operator: 'EXISTS',
    expected_value: 'true',
    unit: null,
    mandatory: false,
    source_page: 8,
    source_text: 'Udyam MSME Registration Certificate is preferred for MSE purchase preference.',
    confidence: 0.88,
    requires_verification: true,
    is_approved: false,
    metadata_json: {},
    created_at: '2026-08-01T10:05:00Z',
  },
];

export const MOCK_BIDDERS: BidderRead[] = [
  {
    id: 'bidder_alpha_01',
    tender_id: 'tender_gem_2026_01',
    bidder_name: 'Alpha Infotech Private Limited',
    gstin: '07AABCA1234H1Z9',
    pan: 'AABCA1234H',
    udyam_number: 'UDYAM-DL-01-0012345',
    cin: 'U72200DL2018PTC123456',
    status: 'QUALIFIED',
    metadata_json: {},
    created_at: '2026-08-15T14:20:00Z',
    documents: [
      {
        id: 'doc_alpha_gst',
        tender_id: 'tender_gem_2026_01',
        bidder_id: 'bidder_alpha_01',
        filename: 'gst_certificate.pdf',
        storage_uri: 'data/uploads/gst_alpha.pdf',
        sha256: 'a1b2c3d4e5f678901234567890abcdef1234567890abcdef1234567890abcdef',
        document_type: 'GST_CERT',
        content_type: 'application/pdf',
        size_bytes: 452100,
        created_at: '2026-08-15T14:21:00Z',
      },
      {
        id: 'doc_alpha_turnover',
        tender_id: 'tender_gem_2026_01',
        bidder_id: 'bidder_alpha_01',
        filename: 'ca_turnover_certificate.pdf',
        storage_uri: 'data/uploads/turnover_alpha.pdf',
        sha256: 'b2c3d4e5f6a178901234567890abcdef1234567890abcdef1234567890abcdef',
        document_type: 'FINANCIAL_STATEMENT',
        content_type: 'application/pdf',
        size_bytes: 812400,
        created_at: '2026-08-15T14:22:00Z',
      },
    ],
  },
  {
    id: 'bidder_bharat_02',
    tender_id: 'tender_gem_2026_01',
    bidder_name: 'Bharat Tech Solutions LLP',
    gstin: '27AAGCB5678K1Z3',
    pan: 'AAGCB5678K',
    udyam_number: 'UDYAM-MH-02-0054321',
    cin: null,
    status: 'PENDING',
    metadata_json: {},
    created_at: '2026-08-16T10:10:00Z',
    documents: [
      {
        id: 'doc_bharat_gst',
        tender_id: 'tender_gem_2026_01',
        bidder_id: 'bidder_bharat_02',
        filename: 'gst_reg_bharat.pdf',
        storage_uri: 'data/uploads/gst_bharat.pdf',
        sha256: 'c3d4e5f6a1b278901234567890abcdef1234567890abcdef1234567890abcdef',
        document_type: 'GST_CERT',
        content_type: 'application/pdf',
        size_bytes: 390200,
        created_at: '2026-08-16T10:12:00Z',
      },
    ],
  },
  {
    id: 'bidder_crest_03',
    tender_id: 'tender_gem_2026_01',
    bidder_name: 'Crest Enterprises',
    gstin: '33AABCC9999P1Z1',
    pan: 'AABCC9999P',
    udyam_number: null,
    cin: null,
    status: 'DISQUALIFIED',
    metadata_json: {},
    created_at: '2026-08-17T11:45:00Z',
    documents: [],
  },
];

export const MOCK_MATRIX_ALPHA: ComplianceMatrixRead = {
  bidder_id: 'bidder_alpha_01',
  tender_id: 'tender_gem_2026_01',
  overall_status: 'PASS',
  run_id: 'run_eval_2026_001',
  historical_limitations_notice: 'Evaluated under live deterministic rules with immutable provenance.',
  rows: [
    {
      requirement_id: 'req_01',
      clause: 'Clause 4.1.1',
      requirement_type: 'GST',
      field: 'tax.gstin',
      operator: 'EQ',
      expected_value: 'VALID_ACTIVE',
      observed_value: 'VALID_ACTIVE',
      status: 'PASS',
      reason_code: 'EXACT_MATCH',
      evidence_ids: ['ev_gst_01'],
      review_required: false,
    },
    {
      requirement_id: 'req_02',
      clause: 'Clause 4.2.3',
      requirement_type: 'TURNOVER',
      field: 'financial.average_annual_turnover',
      operator: 'GTE',
      expected_value: 50000000,
      observed_value: 65000000,
      status: 'PASS',
      reason_code: 'NUMERIC_GTE',
      evidence_ids: ['ev_to_01'],
      review_required: false,
    },
    {
      requirement_id: 'req_03',
      clause: 'Clause 4.3.1',
      requirement_type: 'EXPERIENCE',
      field: 'experience.years',
      operator: 'GTE',
      expected_value: 3,
      observed_value: 5,
      status: 'PASS',
      reason_code: 'NUMERIC_GTE',
      evidence_ids: ['ev_exp_01'],
      review_required: false,
    },
  ],
};

export const MOCK_OVERVIEW: ComplianceOverviewRead = {
  bidder_id: 'bidder_alpha_01',
  tender_id: 'tender_gem_2026_01',
  overall_status: 'PASS',
  human_decision_status: 'QUALIFIED',
};

export const MOCK_REPORT_ALPHA: ReportRead = {
  generated_at: '2026-08-20T12:05:00Z',
  tender: MOCK_TENDERS[0],
  bidder: MOCK_BIDDERS[0],
  compliance_overview: MOCK_OVERVIEW,
  compliance_matrix: MOCK_MATRIX_ALPHA,
  historical_limitations_notice: 'Evaluation completed with zero critical compliance flags.',
  audit_trail_count: 3,
};

export const MOCK_AUDIT_EVENTS: JobEventRead[] = [
  {
    id: 'evt_01',
    job_id: 'job_extract_01',
    stage: 'EXTRACTION',
    status: 'COMPLETED',
    progress: 100,
    message: 'Tender requirements extracted and candidate rules prepared.',
    timestamp: '2026-08-01T10:06:00Z',
  },
  {
    id: 'evt_02',
    job_id: 'job_verify_alpha',
    stage: 'VERIFICATION',
    status: 'COMPLETED',
    progress: 100,
    message: 'Registry verification and multi-document fact validation completed.',
    timestamp: '2026-08-20T11:58:00Z',
  },
  {
    id: 'evt_03',
    job_id: 'job_compliance_alpha',
    stage: 'COMPLIANCE',
    status: 'COMPLETED',
    progress: 100,
    message: 'Deterministic compliance evaluation passed (3/3 rules satisfied).',
    timestamp: '2026-08-20T12:00:00Z',
  },
];

export const MOCK_VERIFICATIONS: VerificationResultRead[] = [
  {
    id: 'vr_01',
    bidder_id: 'bidder_alpha_01',
    field: 'gstin',
    claimed_value: '07AAAAA0000A1Z5',
    verified_value: 'Active (Tax Regular)',
    status: 'VERIFIED',
    source: 'GST_AUTHORIZED_API',
    mode: 'LIVE',
    checked_at: '2026-08-20T11:58:00Z',
    verification_reference: 'GSTN-V-8492019',
  },
  {
    id: 'vr_02',
    bidder_id: 'bidder_alpha_01',
    field: 'udyam_number',
    claimed_value: 'UDYAM-DL-01-0012345',
    verified_value: 'Small Enterprise (Manufacturing)',
    status: 'VERIFIED',
    source: 'UDYAM_AUTHORIZED_API',
    mode: 'LIVE',
    checked_at: '2026-08-20T11:58:10Z',
    verification_reference: 'UDYAM-REG-55219',
  },
  {
    id: 'vr_03',
    bidder_id: 'bidder_alpha_01',
    field: 'cin',
    claimed_value: 'U72200DL2018PTC123456',
    verified_value: 'Active Company',
    status: 'VERIFIED',
    source: 'MCA_AUTHORIZED_API',
    mode: 'LIVE',
    checked_at: '2026-08-20T11:58:15Z',
    verification_reference: 'MCA21-CO-49201',
  },
];

export const MOCK_PROVIDERS: ProviderHealthRead[] = [
  {
    provider_identifier: 'postgresql_pgvector',
    domain: 'DATABASE',
    configured_mode: 'LIVE',
    configuration_status: 'CONFIGURED',
    operational_health: 'AVAILABLE',
    notes: 'HNSW vector cosine search and GIN tsvector hybrid indexes online.',
  },
  {
    provider_identifier: 'gemini_multimodal',
    domain: 'LLM',
    configured_mode: 'LIVE',
    configuration_status: 'CONFIGURED',
    operational_health: 'AVAILABLE',
    notes: 'gemini-1.5-pro and text-embedding-004 connected.',
  },
  {
    provider_identifier: 'ocr_pipeline',
    domain: 'OCR',
    configured_mode: 'LIVE',
    configuration_status: 'CONFIGURED',
    operational_health: 'AVAILABLE',
    notes: 'Multi-format PDF, Word, and Excel parser active.',
  },
];

export const MOCK_SYSTEM_HEALTH: { status: string } = {
  status: 'HEALTHY',
};

export const MOCK_INTEGRATIONS_HEALTH: IntegrationsHealthResponse = {
  gst: { mode: 'LIVE', configured: true, details: 'Tax regular API active' },
  udyam: { mode: 'LIVE', configured: true, details: 'Certificate verification gateway active' },
  mca: { mode: 'LIVE', configured: true, details: 'Company registry status active' },
  epfo: { mode: 'LIVE', configured: true, details: 'EPFO portal active' },
  esic: { mode: 'LIVE', configured: true, details: 'ESIC gateway active' },
  blacklist: { mode: 'LIVE', configured: true, details: 'Central debarment list active' },
  intelligence: { mode: 'LIVE', configured: true, details: 'Hybrid RAG cross-verification online' },
};