class ReasonCode:
    """Canonical reason codes emitted by the deterministic ComplianceEngine."""

    # External Verification Safety Precedence
    VERIFICATION_UNAVAILABLE = "VERIFICATION_UNAVAILABLE"
    CONFLICTING_VERIFICATION_RESULTS = "CONFLICTING_VERIFICATION_RESULTS"
    VERIFICATION_MISMATCH = "VERIFICATION_MISMATCH"
    CONFLICTING_FACTS = "CONFLICTING_FACTS"
    CLAIM_VERIFICATION_MISMATCH = "CLAIM_VERIFICATION_MISMATCH"
    AMBIGUOUS_VERIFIED_VALUE = "AMBIGUOUS_VERIFIED_VALUE"

    # Evidence Existence Precedence
    EVIDENCE_EXISTS = "EVIDENCE_EXISTS"
    EVIDENCE_MISSING = "EVIDENCE_MISSING"
    EVIDENCE_ABSENT = "EVIDENCE_ABSENT"
    EVIDENCE_PRESENT = "EVIDENCE_PRESENT"
    MISSING_EVIDENCE = "MISSING_EVIDENCE"

    # Input Data / Type Error Safety
    OBSERVED_VALUE_NULL = "OBSERVED_VALUE_NULL"
    TYPE_CONVERSION_ERROR = "TYPE_CONVERSION_ERROR"
    MALFORMED_DATE = "MALFORMED_DATE"
    UNSUPPORTED_OPERATOR = "UNSUPPORTED_OPERATOR"

    # Operator Evaluation Success / Failure Outcomes
    EQUAL = "EQUAL"
    NOT_EQUAL = "NOT_EQUAL"
    GREATER_THAN = "GREATER_THAN"
    NOT_GREATER_THAN = "NOT_GREATER_THAN"
    GREATER_THAN_OR_EQUAL = "GREATER_THAN_OR_EQUAL"
    LESS_THAN = "LESS_THAN"
    LESS_THAN_OR_EQUAL = "LESS_THAN_OR_EQUAL"
    NOT_LESS_THAN = "NOT_LESS_THAN"
    COUNT_SUFFICIENT = "COUNT_SUFFICIENT"
    COUNT_INSUFFICIENT = "COUNT_INSUFFICIENT"
    BEFORE_DATE = "BEFORE_DATE"
    ON_OR_AFTER_DATE = "ON_OR_AFTER_DATE"
    AFTER_DATE = "AFTER_DATE"
    ON_OR_BEFORE_DATE = "ON_OR_BEFORE_DATE"
    VALUE_IN_SET = "VALUE_IN_SET"
    VALUE_NOT_IN_SET = "VALUE_NOT_IN_SET"
