"""baseline_argus_schema

Revision ID: 44d5c5ca3f11
Revises: 
Create Date: 2026-09-07 02:00:04.110155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44d5c5ca3f11'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('actor_role', sa.String(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_entity_type'), ['entity_type'], unique=False)

    op.create_table('evidence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=False),
    sa.Column('source_uri', sa.String(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('location_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_entity_type'), ['entity_type'], unique=False)

    op.create_table('processing_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_stage', sa.String(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processing_jobs_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_jobs_target_type'), ['target_type'], unique=False)

    op.create_table('tenders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tender_number', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('authority', sa.String(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('raw_document_uri', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenders_tender_number'), ['tender_number'], unique=True)

    op.create_table('bidders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tender_id', sa.String(), nullable=False),
    sa.Column('bidder_name', sa.String(), nullable=False),
    sa.Column('gstin', sa.String(), nullable=True),
    sa.Column('udyam_number', sa.String(), nullable=True),
    sa.Column('cin', sa.String(), nullable=True),
    sa.Column('pan', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bidders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bidders_bidder_name'), ['bidder_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_bidders_cin'), ['cin'], unique=False)
        batch_op.create_index(batch_op.f('ix_bidders_gstin'), ['gstin'], unique=False)
        batch_op.create_index(batch_op.f('ix_bidders_pan'), ['pan'], unique=False)
        batch_op.create_index(batch_op.f('ix_bidders_tender_id'), ['tender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bidders_udyam_number'), ['udyam_number'], unique=False)

    op.create_table('job_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_events_job_id'), ['job_id'], unique=False)

    op.create_table('tender_requirements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tender_id', sa.String(), nullable=False),
    sa.Column('clause', sa.String(), nullable=False),
    sa.Column('requirement_type', sa.String(), nullable=False),
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('operator', sa.String(), nullable=False),
    sa.Column('expected_value', sa.JSON(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('requires_verification', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tender_requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tender_requirements_field'), ['field'], unique=False)
        batch_op.create_index(batch_op.f('ix_tender_requirements_tender_id'), ['tender_id'], unique=False)

    op.create_table('compliance_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bidder_id', sa.String(), nullable=False),
    sa.Column('tender_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('execution_status', sa.String(), nullable=False),
    sa.Column('overall_status', sa.String(), nullable=True),
    sa.Column('triggered_by', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('rule_version', sa.String(), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['bidder_id'], ['bidders.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_runs_bidder_id'), ['bidder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_runs_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_runs_tender_id'), ['tender_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bidder_id', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('storage_uri', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('sha256', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bidder_id'], ['bidders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_bidder_id'), ['bidder_id'], unique=False)

    op.create_table('human_decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bidder_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reason_code', sa.String(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('officer_id', sa.String(), nullable=False),
    sa.Column('officer_name', sa.String(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bidder_id'], ['bidders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('human_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_human_decisions_bidder_id'), ['bidder_id'], unique=False)

    op.create_table('extracted_facts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('bidder_id', sa.String(), nullable=False),
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bidder_id'], ['bidders.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extracted_facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extracted_facts_bidder_id'), ['bidder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_facts_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_facts_field'), ['field'], unique=False)

    op.create_table('risk_signals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bidder_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('signal_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bidder_id'], ['bidders.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['compliance_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_signals_bidder_id'), ['bidder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_signals_run_id'), ['run_id'], unique=False)

    op.create_table('rule_evaluations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bidder_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('requirement_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reason_code', sa.String(), nullable=False),
    sa.Column('observed_value', sa.JSON(), nullable=True),
    sa.Column('expected_value', sa.JSON(), nullable=True),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('rule_version', sa.String(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bidder_id'], ['bidders.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['tender_requirements.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['compliance_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rule_evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_evaluations_bidder_id'), ['bidder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_evaluations_requirement_id'), ['requirement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_evaluations_run_id'), ['run_id'], unique=False)

    op.create_table('verification_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bidder_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('claimed_value', sa.JSON(), nullable=True),
    sa.Column('verified_value', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.Column('verification_reference', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bidder_id'], ['bidders.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['compliance_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_results_bidder_id'), ['bidder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_results_field'), ['field'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_results_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_results_run_id'))
        batch_op.drop_index(batch_op.f('ix_verification_results_field'))
        batch_op.drop_index(batch_op.f('ix_verification_results_bidder_id'))

    op.drop_table('verification_results')
    with op.batch_alter_table('rule_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_evaluations_run_id'))
        batch_op.drop_index(batch_op.f('ix_rule_evaluations_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_rule_evaluations_bidder_id'))

    op.drop_table('rule_evaluations')
    with op.batch_alter_table('risk_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_signals_run_id'))
        batch_op.drop_index(batch_op.f('ix_risk_signals_bidder_id'))

    op.drop_table('risk_signals')
    with op.batch_alter_table('extracted_facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extracted_facts_field'))
        batch_op.drop_index(batch_op.f('ix_extracted_facts_document_id'))
        batch_op.drop_index(batch_op.f('ix_extracted_facts_bidder_id'))

    op.drop_table('extracted_facts')
    with op.batch_alter_table('human_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_human_decisions_bidder_id'))

    op.drop_table('human_decisions')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_bidder_id'))

    op.drop_table('documents')
    with op.batch_alter_table('compliance_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_runs_tender_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_runs_job_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_runs_created_at'))
        batch_op.drop_index(batch_op.f('ix_compliance_runs_bidder_id'))

    op.drop_table('compliance_runs')
    with op.batch_alter_table('tender_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tender_requirements_tender_id'))
        batch_op.drop_index(batch_op.f('ix_tender_requirements_field'))

    op.drop_table('tender_requirements')
    with op.batch_alter_table('job_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_events_job_id'))

    op.drop_table('job_events')
    with op.batch_alter_table('bidders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bidders_udyam_number'))
        batch_op.drop_index(batch_op.f('ix_bidders_tender_id'))
        batch_op.drop_index(batch_op.f('ix_bidders_pan'))
        batch_op.drop_index(batch_op.f('ix_bidders_gstin'))
        batch_op.drop_index(batch_op.f('ix_bidders_cin'))
        batch_op.drop_index(batch_op.f('ix_bidders_bidder_name'))

    op.drop_table('bidders')
    with op.batch_alter_table('tenders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenders_tender_number'))

    op.drop_table('tenders')
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processing_jobs_target_type'))
        batch_op.drop_index(batch_op.f('ix_processing_jobs_target_id'))

    op.drop_table('processing_jobs')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_entity_type'))
        batch_op.drop_index(batch_op.f('ix_evidence_entity_id'))

    op.drop_table('evidence')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
